services:

  fights-db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ./database/fights-db/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js:ro
  heroes-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ./database/heroes-db/init/heroes.sql:/docker-entrypoint-initdb.d/init.sql:ro

  villains-db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: villains_database
    volumes:
      - ./database/villains-db/init/villains.sql:/docker-entrypoint-initdb.d/init.sql:ro
  locations-db:
    image: mariadb:11.5
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: locations
      MARIADB_PASSWORD: locations
      MARIADB_DATABASE: locations_database
      MARIADB_ROOT_PASSWORD: locations
      MARIADB_SKIP_TEST_DB: yes
    volumes:
      - ./database/locations-db/init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:ro
  heroes:
    build:
      context: services/heroes
    environment:
      DATABASE_URL: "postgres://superman:superman@heroes-db:5432/heroes_database"
    ports:
      - "8001:8000"

  villains:
    build: 
      context: services/villains
    environment:
      DATABASE_URL: "postgres://superman:superman@villains-db:5432/villains_database"
    ports:
      - "8002:8000"

  locations:
    build: 
      context: services/locations
    environment:
      MYSQL_URL: "mysql://locations:locations@locations-db/locations_database"
    ports:
      - "8003:8000"

  fights:
    build: 
      context: services/fights
    ports:
      - "8004:8000"
  k6:
    build: k6-image
    environment:
      K6_HOST: http://fights:8000
    command: ["bash", "-c", "while true; do sleep 3600; done"]
    volumes:
      - ./k6:/k6:ro
      - ./k6/results:/results
      # k6:
      # build: k6-image
      # environment:
      #   K6_HOST: http://fights:8000 
      # command: ["bash", "-c", "while true; do sleep 3600; done"]
      # volumes:
      #   - ./k6:/k6:ro
      #   - ./k6/results:/results
